import React, { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { AnalysisStatus } from '../types';
import { Bot, FileText, Printer } from 'lucide-react';

interface AnalysisBoxProps {
  analysis: string;
  status: AnalysisStatus;
}

export const AnalysisBox: React.FC<AnalysisBoxProps> = ({ analysis, status }) => {
  const [displayedText, setDisplayedText] = useState('');
  
  // Typewriter effect
  useEffect(() => {
    if (status === AnalysisStatus.COMPLETE && analysis) {
      setDisplayedText('');
      let i = 0;
      const speed = 15; // ms per char
      
      const intervalId = setInterval(() => {
        setDisplayedText(analysis.slice(0, i));
        i++;
        if (i > analysis.length) {
          clearInterval(intervalId);
        }
      }, speed);
      
      return () => clearInterval(intervalId);
    }
  }, [analysis, status]);

  if (status === AnalysisStatus.IDLE || status === AnalysisStatus.ERROR) return null;

  return (
    <div className="w-full bg-white border border-slate-200 rounded-lg overflow-hidden flex flex-col h-full animate-fade-in ring-1 ring-slate-900/5">
      {/* Header */}
      <div className="bg-slate-50 px-5 py-3 border-b border-slate-200 flex items-center justify-between flex-shrink-0">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-white border border-slate-200 rounded-md shadow-sm">
             <FileText size={16} className="text-fap-600" />
          </div>
          <span className="font-bold text-slate-700 text-xs uppercase tracking-widest">Analyst Report // $FAP</span>
        </div>
        <div className="flex items-center gap-2 text-xs text-slate-400 font-mono">
          <Printer size={14} />
          <span>CONFIDENTIAL</span>
        </div>
      </div>
      
      {/* Content */}
      <div className="p-6 flex-1 font-mono text-slate-800 overflow-y-auto bg-white relative">
        {status === AnalysisStatus.ANALYZING || status === AnalysisStatus.FETCHING_DATA ? (
          <div className="flex flex-col items-center justify-center h-full space-y-6">
             <div className="relative">
                <div className="w-16 h-16 rounded-full border-4 border-slate-100 border-t-fap-600 animate-spin"></div>
                <img 
                  src="https://wkkeyyrknmnynlcefugq.supabase.co/storage/v1/object/public/neww/fap.png" 
                  className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-10 h-10 rounded-full border-2 border-white shadow-sm" 
                  alt="Loading"
                />
             </div>
             <div className="space-y-2 text-center">
                <p className="text-slate-900 font-bold text-sm tracking-widest animate-pulse">
                   {status === AnalysisStatus.FETCHING_DATA ? "ESTABLISHING BLOCKCHAIN UPLINK" : "PROCESSING FINANCIAL METRICS"}
                </p>
                <p className="text-slate-400 text-xs">Please wait while the pussy analyzes the charts...</p>
             </div>
          </div>
        ) : (
          <div className="prose prose-sm prose-slate max-w-none">
             <div className="mb-4 pb-4 border-b border-slate-100 flex items-center justify-between">
                <span className="text-xs text-slate-400 uppercase">Generated by AI Terminal</span>
                <span className="text-xs font-bold text-fap-600 bg-fap-50 px-2 py-1 rounded">FINAL VERDICT READY</span>
             </div>
             <ReactMarkdown 
               components={{
                 strong: ({node, ...props}) => <span className="font-bold text-fap-700 bg-fap-50 px-1 rounded-sm" {...props} />
               }}
             >
               {displayedText}
             </ReactMarkdown>
             {displayedText.length < analysis.length && (
               <span className="inline-block w-2 h-4 bg-fap-600 ml-1 animate-pulse align-middle"></span>
             )}
          </div>
        )}
      </div>
      
      {/* Footer of the box */}
      <div className="bg-slate-50 px-5 py-2 border-t border-slate-200 text-[10px] text-slate-400 font-mono flex justify-between uppercase flex-shrink-0">
        <span>ID: {Math.random().toString(36).substr(2, 9).toUpperCase()}</span>
        <span>Secure Connection</span>
      </div>
    </div>
  );
};